"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import { Download, Loader2, FileText, Users, BookOpen } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { getScoreBadge } from "@/lib/utils";
import type { Subject } from "@/types/database";
import type { StudentWithNisn, GradeWithDetails } from "../page";

interface PdfToolProps {
  onBack: () => void;
  grades: GradeWithDetails[];
  subjects: Subject[];
  students: StudentWithNisn[];
  className: string;
}

export function PdfTool({ onBack, grades, subjects, students, className }: PdfToolProps) {
  const [generating, setGenerating] = useState(false);
  const [semester, setSemester] = useState("Genap 2025/2026");
  const [selectedSubject, setSelectedSubject] = useState<string>("all");

  const filteredGrades = selectedSubject === "all" ? grades : grades.filter((g) => g.subject_id === selectedSubject);

  // Build student summary
  const studentMap: Record<string, { name: string; scores: number[]; subjects: string[] }> = {};
  filteredGrades.forEach((g) => {
    if (!studentMap[g.student_id]) {
      studentMap[g.student_id] = { name: g.student_name, scores: [], subjects: [] };
    }
    studentMap[g.student_id].scores.push(g.score);
    studentMap[g.student_id].subjects.push(g.subject_name);
  });

  const studentSummary = Object.values(studentMap).map((s) => ({
    name: s.name,
    avg: s.scores.reduce((a, b) => a + b, 0) / s.scores.length,
    count: s.scores.length,
  })).sort((a, b) => b.avg - a.avg);

  const generatePdf = async () => {
    setGenerating(true);
    try {
      const { jsPDF } = await import("jspdf");
      const doc = new jsPDF();

      doc.setFontSize(18);
      doc.setFont("helvetica", "bold");
      doc.text("LAPORAN NILAI SISWA", 105, 20, { align: "center" });

      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      doc.text(`Kelas: ${className}`, 20, 35);
      doc.text(`Semester: ${semester}`, 20, 42);
      doc.text(`Tanggal: ${new Date().toLocaleDateString("id-ID")}`, 20, 49);
      if (selectedSubject !== "all") {
        const sub = subjects.find((s) => s.id === selectedSubject);
        doc.text(`Mata Pelajaran: ${sub?.name ?? "-"}`, 20, 56);
      }

      doc.setLineWidth(0.5);
      doc.line(20, 62, 190, 62);

      const startY = 72;
      doc.setFontSize(10);
      doc.setFont("helvetica", "bold");
      doc.setFillColor(99, 102, 241);
      doc.rect(20, startY - 6, 170, 10, "F");
      doc.setTextColor(255, 255, 255);
      doc.text("No", 25, startY);
      doc.text("Nama Siswa", 40, startY);
      doc.text("Jml Nilai", 130, startY);
      doc.text("Rata-rata", 160, startY);

      doc.setTextColor(0, 0, 0);
      doc.setFont("helvetica", "normal");

      studentSummary.forEach((s, i) => {
        const y = startY + 12 + i * 9;
        if (i % 2 === 0) {
          doc.setFillColor(245, 245, 255);
          doc.rect(20, y - 5, 170, 9, "F");
        }
        doc.text(`${i + 1}`, 25, y);
        doc.text(s.name, 40, y);
        doc.text(`${s.count}`, 130, y);
        doc.setFont("helvetica", "bold");
        doc.text(s.avg.toFixed(1), 160, y);
        doc.setFont("helvetica", "normal");
      });

      const footerY = startY + 12 + studentSummary.length * 9 + 15;
      doc.setFontSize(9);
      doc.setTextColor(128, 128, 128);
      doc.text("Generated by EduFlow — Personal Learning OS", 105, footerY, { align: "center" });

      doc.save(`Laporan_Nilai_${className}_${semester.replace(/\//g, "-")}.pdf`);
    } catch (err) {
      console.error("PDF generation error:", err);
    } finally {
      setGenerating(false);
    }
  };

  return (
    <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="space-y-6">
      <div className="flex items-center gap-3">
        <Button variant="ghost" onClick={onBack}>← Kembali</Button>
        <h2 className="text-xl font-bold">Laporan Nilai PDF</h2>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <Card className="lg:col-span-1">
          <CardHeader><CardTitle className="text-base">Pengaturan</CardTitle></CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <Label>Semester</Label>
              <Input value={semester} onChange={(e) => setSemester(e.target.value)} />
            </div>
            <div className="space-y-2">
              <Label>Filter Mata Pelajaran</Label>
              <select
                value={selectedSubject}
                onChange={(e) => setSelectedSubject(e.target.value)}
                className="w-full h-10 px-3 rounded-md border border-input bg-background text-sm"
              >
                <option value="all">Semua Mata Pelajaran</option>
                {subjects.map((s) => (
                  <option key={s.id} value={s.id}>{s.name}</option>
                ))}
              </select>
            </div>
            <div className="flex gap-2 text-sm text-muted-foreground">
              <Users className="h-4 w-4 mt-0.5 shrink-0" />
              <span>{studentSummary.length} siswa · {filteredGrades.length} data nilai</span>
            </div>
            <Button onClick={generatePdf} disabled={generating || studentSummary.length === 0} className="w-full">
              {generating ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Download className="mr-2 h-4 w-4" />}
              Download PDF
            </Button>
            {studentSummary.length === 0 && (
              <p className="text-xs text-amber-500">Belum ada data nilai untuk diekspor.</p>
            )}
          </CardContent>
        </Card>

        <Card className="lg:col-span-2">
          <CardHeader><CardTitle className="text-base flex items-center gap-2"><BookOpen className="h-4 w-4" />Preview Laporan</CardTitle></CardHeader>
          <CardContent>
            {studentSummary.length > 0 ? (
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="border-b border-border/50">
                      <th className="text-left py-2 px-3 text-muted-foreground font-medium">#</th>
                      <th className="text-left py-2 px-3 text-muted-foreground font-medium">Nama Siswa</th>
                      <th className="text-center py-2 px-3 text-muted-foreground font-medium">Jumlah Nilai</th>
                      <th className="text-center py-2 px-3 text-muted-foreground font-medium">Rata-rata</th>
                      <th className="text-center py-2 px-3 text-muted-foreground font-medium">Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    {studentSummary.map((s, i) => {
                      const badge = getScoreBadge(s.avg);
                      return (
                        <tr key={s.name} className="border-b border-border/30 last:border-0">
                          <td className="py-2 px-3 text-muted-foreground">{i + 1}</td>
                          <td className="py-2 px-3 font-medium">{s.name}</td>
                          <td className="py-2 px-3 text-center">{s.count}</td>
                          <td className="py-2 px-3 text-center font-semibold">{s.avg.toFixed(1)}</td>
                          <td className="py-2 px-3 text-center"><Badge className={badge.color}>{badge.label}</Badge></td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            ) : (
              <div className="flex flex-col items-center justify-center py-12 text-muted-foreground">
                <FileText className="h-12 w-12 mb-3 opacity-20" />
                <p>Belum ada data nilai</p>
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </motion.div>
  );
}
